name: CAVE
favicon: null
layout_spectrum: 0
typography_spectrum: 0.23209
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 1
  lightness: 0.28726619738154113
  saturation: 0.19927146704867482
  rhythmicContrast: 0.5
purpose: []
